services:
  postgres:
    image: postgres:15
    container_name: visiontech_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: visiontech_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - visiontech_network

volumes:
  postgres_data:

networks:
  visiontech_network: